---
- name: Setup and install packages on Ubuntu
  hosts: local
  become: yes
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Install development tools
      apt:
        name: 
          - git
          - curl
          - vim
        state: present

    - name: Install system tools
      apt:
        name:
          - htop
          - tree
        state: present

    - name: Install networking tools
      apt:
        name: net-tools
        state: present

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Node.js and npm
      apt:
        name: 
          - nodejs
          - npm
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Clean up
      apt:
        autoremove: yes
        autoclean: yes
